# Generated by Django 5.1.6 on 2025-03-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_safe_eyes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='busy',
            field=models.IntegerField(choices=[(1, '余裕がある'), (2, '普通'), (3, '忙しい')], default=2),
        ),
    ]
