# Generated by Django 5.2.3 on 2025-06-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('spirit', 'スピリット'), ('ultimate', 'アルティメット'), ('brave', 'ブレイヴ'), ('nexus', 'ネクサス'), ('magic', 'マジック')], max_length=10)),
                ('cost', models.IntegerField()),
                ('reduction_symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('color', models.CharField(max_length=10)),
                ('race', models.CharField(blank=True, max_length=20, null=True)),
                ('effect_text', models.TextField(blank=True, null=True)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('flavor_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
