# Generated by Django 5.2.3 on 2025-06-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_byzer_game', '0002_card_explain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['priority']},
        ),
        migrations.AddField(
            model_name='card',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
