# Generated by Django 5.2.3 on 2025-06-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_byzer_game', '0003_alter_card_options_card_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='priority',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
