# Generated by Django 5.2.3 on 2025-06-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_byzer_game', '0004_alter_card_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='race',
        ),
    ]
