# Generated by Django 5.2.3 on 2025-06-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_byzer_game', '0005_remove_card_race'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='race',
            field=models.ManyToManyField(related_name='races', to='app_byzer_game.race'),
        ),
    ]
