# Generated by Django 5.2.3 on 2025-07-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_byzer_game', '0006_race_card_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='priority',
            field=models.PositiveIntegerField(db_index=True, verbose_name='move'),
        ),
    ]
