# Generated by Django 5.2.3 on 2025-07-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_byzer_game', '0007_race_order_alter_card_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='race',
            field=models.ManyToManyField(blank=True, related_name='races', to='app_byzer_game.race'),
        ),
    ]
