# Generated by Django 5.2.3 on 2025-07-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_byzer_game', '0008_alter_card_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
