# Generated by Django 5.2.3 on 2025-07-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_byzer_game', '0009_alter_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.CharField(choices=[('スピリット', 'スピリット'), ('アルティメット', 'アルティメット'), ('ブレイヴ', 'ブレイヴ'), ('ネクサス', 'ネクサス'), ('マジック', 'マジック')], max_length=10),
        ),
    ]
