# Generated by Django 5.2.3 on 2025-07-01 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_byzer_game', '0010_alter_card_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='race1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race1_cards', to='app_byzer_game.race'),
        ),
        migrations.AddField(
            model_name='card',
            name='race2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race2_cards', to='app_byzer_game.race'),
        ),
        migrations.AddField(
            model_name='card',
            name='race3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race3_cards', to='app_byzer_game.race'),
        ),
    ]
