# Generated by Django 5.2.3 on 2025-08-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_byzer_game', '0012_remove_card_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='expansion',
            field=models.CharField(blank=True, choices=[(1, '1stExpantion')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='priority',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
