# Generated by Django 5.2.3 on 2025-08-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_byzer_game', '0013_card_expansion_alter_card_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expansion',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='priority',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
